Added HomePage, Navbar , Header
itsKhadeer/Events-Website pull request #5
Opened 2024-01-29 21:21 UTC by A-nirvana

I have added the Homepage the navbar and the header  just like the provided design. I have also made it responsive to work on phone.
![Screenshot (30)](https://github.com/itsKhadeer/Events-Website/assets/145558376/ce8ad03b-93a0-4f7d-8377-59b5d0c15e0c)

2024-01-29 21:23 UTC, A-nirvana commented
I am building the events page. Tell me what I can improve in this page and give me ideas for the next one please.

2024-03-03 09:12 UTC, itsKhadeer commented
![image](https://github.com/itsKhadeer/Events-Website/assets/119066611/31edef19-65cf-4552-bc91-2e8967091982)

-  [ ] fix this overflow in the teams page and also reduce the size of the blue box,

- [ ] in the swiper, don't fix the blue box as background img, make it swipe along with the content, like a card.

-  [ ] also the teams page ui is not responsive for iphone se, take iphone se as reference for making the ui mobile responsive, fix it.

- [ ] Add teams page in navbar and also remove unnecessary fields in navbar and add the important onces,

- [ ] Add animation for the navbar (when it opens and closes) 

- [ ] try to add more components instead of writing your whole code in the pages, for example you can make the swiper as a component.

![image](https://github.com/itsKhadeer/Events-Website/assets/119066611/2e7ff088-4b31-411c-95b1-aae9eeac4732)
- [ ] fix this over lapping of buttons in the home page

![image](https://github.com/itsKhadeer/Events-Website/assets/119066611/5aa3b38e-c8d4-4e0b-983b-b3e8f729537b)
- [ ] fix this overflow here in the above image

- [ ] after making your changes please test properly.

2024-03-03 20:48 UTC, itsKhadeer requested changes
please complete the changes

2024-03-03 20:48 UTC, itsKhadeer commented on src/pages/OurTeam/OurTeam.tsx
try to make the swiper as a seperate component instead of directly implementing it here

2024-03-17 13:53 UTC, A-nirvana commented
@itsKhadeer I have made the requested changes please review these changes and tell me if there's any problem.

2024-03-17 15:28 UTC, itsKhadeer approved these changes

2024-03-17 15:28 UTC, merged